[#10] Implement the authentication - server
szymon-konieczny/threatsmarker pull request #26
Opened 2020-01-05 01:40 UTC by szymon-konieczny

#10

2020-01-05 14:49 UTC, Drajvon requested changes

2020-01-05 14:49 UTC, Drajvon commented on server/src/features/auth/auth.controller.ts
> +    this.bcrypt = new Bcrypt();
Nie musisz robić tego w constructorze bo on nie potrzebnie zaśmieca kod możesz zrobić po prostu `public bcrypt = new Bcrypt()`

2020-01-05 14:49 UTC, Drajvon commented on server/src/features/auth/auth.controller.ts
> +      return next({ error: 'User already exists!' });
Fajnie jakbyś dodawał jeszcze kody błędów w stylu `USER_ALREADY_EXISTS` to pozwoli Ci je mapować w łatwy sposób w przyszłości

2020-01-05 14:49 UTC, Drajvon commented on server/src/features/auth/auth.controller.ts
> +  public async register(req: Request, res: Response, next: NextFunction) {
Masz tutaj za dużo logiki, powinieneś wywoływać tylko `userService.registerUser()` i zwracać to co zwórci Ci ta metoda, całą logike przenieś do serwisu w contollerach staraj się miec jak najmniej kodu

2020-01-05 14:49 UTC, Drajvon commented on server/src/features/auth/auth.controller.ts
> +      const arePasswordsMatching = await this.bcrypt.comparePasswords(password, user.password);
A co jak user nie istnieje? Wtedy `user.password` wywali error

2020-01-05 14:49 UTC, Drajvon commented on server/src/features/auth/auth.controller.ts
> +        return next({ error: 'Login failed! Check authentication credentials' });
Przekazujesz jakoś statusy responsu do error handlera?

2020-01-05 14:49 UTC, Drajvon commented on server/src/features/auth/auth.controller.ts
> +      res.json({ user, token });
Token lepiej zwracać w cookie z flaga httpOnly i secure, to jest o wiele bezpieczniejsze

2020-01-05 14:49 UTC, Drajvon commented on server/src/features/auth/auth.service.ts
> +  public generateAuthToken(userId: string): string {
Nie potrzebnie masz abstrakcje abstakcji

2020-01-05 14:49 UTC, Drajvon commented on server/src/features/auth/auth.service.ts
> +  constructor() {
Tak jak wczesniej

2020-01-05 14:49 UTC, Drajvon commented on server/src/features/auth/auth.service.ts
> +  public async hashPassword(password: string): Promise<string> {
Tutaj tez masz abstrakcje abstrakcji

2020-01-05 14:49 UTC, Drajvon commented on server/src/features/auth/index.ts
> +authRouter.post('/', authController.login);
2 razy to samo?

2020-01-05 14:49 UTC, Drajvon commented on server/src/features/users/users.controller.ts
> +  public async registerUser(req: Request, res: Response, next: NextFunction): Promise<void> {
To powinno być w features/auth/auth.controller

2020-01-05 14:49 UTC, Drajvon commented on server/src/features/users/users.service.ts
> +  public async registerUser(userData: Partial<User>): Promise<User> {
Bardziej `createUser` user service nie powinien wiedzieć w jaki sposób tworzyć usera, on ma go tylko stworzyc niezależnie od kontekstu

2020-01-05 14:49 UTC, Drajvon commented on server/src/features/users/users.service.ts
> +    const hashedPassword = await authService.hashPassword(userData.password);
Cały proces rejestracji powinien być w `auth`. Teraz masz circular dependencie bo importujesz users do auth i auth do users

2020-01-05 14:49 UTC, Drajvon commented on server/src/utils/jwt.ts
> +  public sign(userId: string): string {
Tutaj dałbym zamiast userId po prostu obiekt, bo nie będziesz wykorzystywał tego serwisu tylko do autoryzacji

2020-01-06 01:48 UTC, szymon-konieczny commented on server/src/utils/jwt.ts
> +  public sign(userId: string): string {
Masz na myśli coś takiego?
```suggestion
  public sign(config: Object): string {
      return jwt.sign(config, env.SECRET_KEY);
  }
```

2020-01-06 01:57 UTC, szymon-konieczny commented on server/src/features/auth/auth.service.ts
> +  public generateAuthToken(userId: string): string {
`auth.service.ts` jest w takim razie niepotrzebny i będę bezpośrednio korzystał np. z `this.jwt.sign({ userId })`

2020-01-06 01:59 UTC, szymon-konieczny commented on server/src/features/auth/auth.service.ts
> +  public generateAuthToken(userId: string): string {
tak samo z `this.bcrypt.hashPassword(password)`

2020-01-06 15:05 UTC, Drajvon requested changes

2020-01-06 15:05 UTC, Drajvon commented on server/src/features/auth/auth.controller.ts
> +const cookieWithTokenName = 'Token';
To wywal do configu

2020-01-06 15:05 UTC, Drajvon commented on server/src/features/auth/auth.service.ts
> +  public async getNewUserConfig(userData: User): Promise<User> {
O co chodzi z tym configiem?

2020-01-06 15:05 UTC, Drajvon commented on server/src/helpers/getUpdatedConfig.ts
> +export const getUpdatedConfig = <T>(defaultConfig: T, configUpdate?: Partial<T>): T => ({
Ten helper nie ma sensu

2020-01-06 15:05 UTC, Drajvon commented on server/src/utils/jwt.ts
> +  public sign(config: any): string {
W tym serwisie użyłbym generyka zamiast dawać `any` i `string | object`

2020-01-06 15:05 UTC, Drajvon commented on server/src/features/auth/auth.service.ts
> +  public setCookie(res: Response, name: string, value: string): void {
Ustawiaj cookie w controlerze, a config wywal do configu

2020-01-06 15:05 UTC, Drajvon commented on server/src/features/auth/auth.service.ts
> +  public async getNewUserConfig(userData: User): Promise<User> {
Nie zwracasz tutaj configu tylko usera

2020-01-06 15:05 UTC, Drajvon commented on server/src/features/users/users.service.ts
>      return await this.getUser(id);
Czy jeśli zwracasz usera to usuwasz z niego `password`? To jest must have, nie mozesz zwracać hasła, nawet jeśli jest zaszyfrowane

2020-01-06 15:05 UTC, Drajvon commented on server/src/features/auth/auth.controller.ts
> +    try {
To wszystko powinno być w servisie

2020-01-06 15:05 UTC, Drajvon commented on server/src/features/auth/auth.controller.ts
> +      authService.setCookie(res, cookieWithTokenName, token);
Tutaj powinno zostać tylko ustawianie cookie i response

2020-01-06 15:05 UTC, Drajvon commented on server/src/features/auth/auth.controller.ts
> +  public async login(req: Request, res: Response, next: NextFunction): Promise<void> {
To wszystko powinno być w serwisie

2020-01-10 21:15 UTC, purbanski-deftcode requested changes

2020-01-10 21:15 UTC, purbanski-deftcode commented on server/src/constants/messages.ts
> +  migrationOK = 'DB migration OK',
Wincyj konsekwencji. Enumy pisz z dużej camelCasem tak samo klucze.

2020-01-10 21:15 UTC, purbanski-deftcode commented on server/src/features/auth/auth.service.ts
> +      // maxAge: 1000000000, // ttl in ms (remove this option and cookie will die when browser is closed)
Nawiązujac do komentarza napewno chcesz żeby ciasteczko umierało wraz z zamykaniem przeglądarki?

2020-01-10 21:15 UTC, purbanski-deftcode commented on server/src/features/auth/auth.service.ts
> +      secure: true, // to force https (if you use it)
Możesz mieć problem z testowaniem na froncie tego. Albo musisz zrobić wtedy HTTPS na froncie (chyba AngularCLI pozwala) albo tutaj warunkowo wymuszać secure tylko na prodzie.

2020-01-10 21:15 UTC, purbanski-deftcode commented on server/src/features/users/users.router.ts
> +    usersRouter.get('/', this.usersController.getAll.bind(this.usersController));
Możesz stworzyć na to ładną abstrakcję. A nawet użyć dziedziczenia albo kompozycji albo inicjować generyczny router i używać jego metod. Wiele różnych podejść zamiast zawsze pisać ręcznie `.bind`

2020-10-28 21:18 UTC, merged